CREATE TABLE Team(
	TeamID INT NOT NULL,
	School VARCHAR2(50) NOT NULL,
	Abbreviation VARCHAR2(20),
	PRIMARY KEY(TeamID)
);
CREATE TABLE Player(
	PlayerID INT NOT NULL,
	FirstName VARCHAR2(50),
	LastName VARCHAR2(50),
	Position VARCHAR2(20),
	Weight INT,
	Year INT,
	JerseyNo INT,
	Height INT,
	PRIMARY KEY(PlayerID)
);
CREATE TABLE Coach(
	CoachID INT GENERATED ALWAYS AS IDENTITY,
	FirstName VARCHAR2(50),
	LastName VARCHAR2(50),
	PRIMARY KEY(CoachID)
);
CREATE TABLE Conference(
	ConferenceID INT NOT NULL,
	ShortName VARCHAR2(50),
	Name VARCHAR2(100),
	Classification VARCHAR2(20),
	Abbreviation VARCHAR2(20),
	PRIMARY KEY(ConferenceID)
);
CREATE TABLE Game(
	GameID INT NOT NULL,
	StartDateTime DATE,
	Week INT,
	Season INT,
	HomeTeam INT NOT NULL,
	HomePoints INT,
	AwayTeam INT NOT NULL,
	AwayPoints INT,
	IsCompleted NUMBER(1),
	IsPostseason NUMBER(1),
	PRIMARY KEY(GameID),
   	FOREIGN KEY(HomeTeam) REFERENCES Team(TeamID),
    FOREIGN KEY(AwayTeam) REFERENCES Team(TeamID)
);
CREATE TABLE DraftPick(
	DraftPickID INT GENERATED ALWAYS AS IDENTITY,
	PlayerID INT NOT NULL,
	CollegeTeam INT NOT NULL,
	NFLTeam VARCHAR2(50),
	Position VARCHAR2(20),
	Year INT,
	Round INT,
	RoundPick INT,
	OverallPick INT,
	PRIMARY KEY(DraftPickID),
	FOREIGN KEY(PlayerID) REFERENCES Player(PlayerID),
	FOREIGN KEY(CollegeTeam) REFERENCES Team(TeamID)
);
CREATE TABLE Roster(
	TeamID INT NOT NULL,
	PlayerID INT NOT NULL,
	Season INT NOT NULL,
	PRIMARY KEY(PlayerID, TeamID, Season),
	FOREIGN KEY(PlayerID) REFERENCES Player(PlayerID),
	FOREIGN KEY(TeamID) REFERENCES Team(TeamID)
);
CREATE TABLE Poll(
	PollID INT GENERATED ALWAYS AS IDENTITY,
	PollName VarChar2(50),
	TeamID INT NOT NULL,
	Season INT,
	Week INT,
	Rank INT NOT NULL,
	IsPostseason NUMBER(1),
	PRIMARY KEY(PollID),
	FOREIGN KEY(TeamID) REFERENCES Team(TeamID)
);
CREATE TABLE CoachingRecord(
	CoachID INT NOT NULL,
	TeamID INT NOT NULL,
	Year INT NOT NULL,	
	Games INT,
	Wins INT,
	Losses INT,
	Ties INT,
	PRIMARY KEY(CoachID, TeamID, Year),
	FOREIGN KEY(CoachID) REFERENCES Coach(CoachID),
	FOREIGN KEY(TeamID) REFERENCES Team(TeamID)
);
CREATE TABLE ConferenceMembership(
	Year INT NOT NULL,
	TeamID INT NOT NULL,
	ConferenceID INT NOT NULL,
	PRIMARY KEY(ConferenceID, TeamID, Year),
	FOREIGN KEY(ConferenceID) REFERENCES Conference(ConferenceID),
	FOREIGN KEY(TeamID) REFERENCES Team(TeamID)
);
CREATE TABLE TeamGameStat(
	StatID INT GENERATED ALWAYS AS IDENTITY,
	StatValue NUMBER,
	StatCategory INT NOT NULL,
	Game INT NOT NULL,
	Team INT NOT NULL,
	PRIMARY KEY(StatID),
	FOREIGN KEY (Game) REFERENCES Game(GameID),
	FOREIGN KEY (Team) REFERENCES Team(TeamID),
	FOREIGN KEY (StatCategory) REFERENCES StatCategory(ID)
);	
CREATE TABLE PlayerSeasonStat(
	StatID INT GENERATED ALWAYS AS IDENTITY,
	StatValue NUMBER,
	StatType INT NOT NULL,
	StatCategory INT NOT NULL,
	Season INT NOT NULL,
	Player INT NOT NULL,
	PRIMARY KEY(StatID),
	FOREIGN KEY (Player) REFERENCES Player(PlayerID),
	FOREIGN KEY (StatType) REFERENCES StatType(ID),
	FOREIGN KEY (StatCategory) REFERENCES StatCategory(ID)
);
CREATE TABLE PlayerGameStat(
	StatID INT GENERATED ALWAYS AS IDENTITY,
	StatValue NUMBER,
	StatType INT NOT NULL,
	StatCategory INT NOT NULL,
	Game INT NOT NULL,
	Player INT NOT NULL,
	PRIMARY KEY(StatID),
	FOREIGN KEY (Game) REFERENCES Game(GameID),
	FOREIGN KEY (Player) REFERENCES Player(PlayerID),
	FOREIGN KEY (StatType) REFERENCES StatType(ID),
	FOREIGN KEY (StatCategory) REFERENCES StatCategory(ID)
);

CREATE TABLE StatCategory(
	ID INT GENERATED ALWAYS AS IDENTITY,
	Category VARCHAR2(20),
	PRIMARY KEY(ID)
);

CREATE TABLE StatType(
	ID INT GENERATED ALWAYS AS IDENTITY,
	Type VARCHAR2(20),
	PRIMARY KEY(ID)
);